### ISSUE TITLE
got error when cdebug pod in cluster

### ISSUE THREAD

**Issue by jxs1211** [iximiuz/cdebug#62]
I run pod using distroless as base image on EKS. I got error using cdebug like below:
```shell
➜  playground kg pod
NAME                                                    READY   STATUS    RESTARTS      AGE
cloudshell-worker-l847tmh7f2                            1/1     Running   0             3d23h
cloudtty-operator-controller-manager-77674f78c4-mbt9m   1/1     Running   0             4d5h
my-debugger                                             2/2     Running   1 (30h ago)   30h
nginx-deployment-7c79c4bf97-f2dhp                       1/1     Running   0             2d2h
nginx-deployment-7c79c4bf97-f52pj                       1/1     Running   0             2d2h
➜  playground cdebug exec -it pod/cloudtty-operator-controller-manager-77674f78c4-mbt9m/cloudtty-operator-controller-manager       
Debugger container name: cdebug-00881441
Starting debugger container...
Waiting for debugger container...
ln: /proc/1/root/.cdebug-00881441: Permission denied
cdebug: Debugger container "cdebug-00881441" terminated: Error -  (exit code: 1).
➜  playground cdebug exec -it --image=nixery.dev/shell/vim/ps/tshark pod/cloudtty-operator-controller-manager-77674f78c4-mbt9m/cloudtty-operator-controller-manager
Debugger container name: cdebug-5c2966f5
Starting debugger container...
Waiting for debugger container...
rm: cannot remove '/proc/1/root/nix': Permission denied
cdebug: Debugger container "cdebug-5c2966f5" terminated: Error -  (exit code: 1).
➜  playground 
```

**Comment by iximiuz** [comment]
Hey, thanks for the report! Have you tried using the `--privileged` flag?

Example: `cdebug exec --privileged -it pod/cloudtty-operator-controller-manager-77674f78c4-mbt9m/cloudtty-operator-controller-manager`

**Comment by jxs1211** [comment]
> Hey, thanks for the report! Have you tried using the `--privileged` flag?
> 
> Example: `cdebug exec --privileged -it pod/cloudtty-operator-controller-manager-77674f78c4-mbt9m/cloudtty-operator-controller-manager`

Yes, it works with `--privileged` flag, thanks for your help. Excellent debug tool by the way.

**Comment by jxs1211** [comment]
> > Hey, thanks for the report! Have you tried using the `--privileged` flag?
> > Example: `cdebug exec --privileged -it pod/cloudtty-operator-controller-manager-77674f78c4-mbt9m/cloudtty-operator-controller-manager`
> 
> Yes, it works with `--privileged` flag, thanks for your help. I think always using the flag can avoid this kind of issue.

**Comment by iximiuz** [comment]
That's neat! However, `kubectl` probably works in your case because the target Pod already has the required credentials to access the Kubernetes API. It'd be a bit bizarre and scary if `kubectl` worked from any Pod.

**Comment by jxs1211** [comment]
> That's neat! However, `kubectl` probably works in your case because the target Pod already has the required credentials to access the Kubernetes API. It'd be a bit bizarre and scary if `kubectl` worked from any Pod.

That's good to know! I'm currently working on integrating cdebug to enhance the debugging experience. I noticed the design for now it's not that sound, does that mean that `cdebug exec` might have breaking changes in the future?

**Comment by iximiuz** [comment]
Could you elaborate on what parts of the current design you find the most rough? There are, of course, some missing flags and perhaps even bigger features, but I find the existing capabilities and the way to access them rather handy. Haven't been planning to change what's already there much. Mainly bug fixes and additions.
